DELETE FROM eis_skill_category;
INSERT INTO eis_skill_category (scid, scname) VALUES ( 1, 'Programming Language');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 2, 'Queuing');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 3, 'Framework & 3rd Party Lib');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 4, 'Platform');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 5, 'Operating System');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 6, 'RDBMS');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 7, 'App Server');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 8, 'Technology');
INSERT INTO eis_skill_category (scid, scname) VALUES ( 9, 'Data Handling');
INSERT INTO eis_skill_category (scid, scname) VALUES (10, 'Portal');
INSERT INTO eis_skill_category (scid, scname) VALUES (11, 'BI and Reporting');
INSERT INTO eis_skill_category (scid, scname) VALUES (12, 'Product');

DELETE FROM eis_skill_item;
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'ASP');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'ASP.NET');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'C#');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'C/C++');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'COBOL');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'HTML');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'Java');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'JavaScript');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'JAXB/XMLBeans');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'JSP');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'OpenEdge ABL');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'Oracle Forms');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'PL/SQL');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'Pro*C');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'SQL');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'UniVerse DataBasic');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'VB');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'VB.NET');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'XML');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'XPath');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'XQuery');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (1, 'XSLT');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (2, 'AMQP');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (2, 'JMS');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (2, 'MQ');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (2, 'MSMQ');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Ajax');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'AppFuse');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Dojo');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'EJB');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Fade/Topaz');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'GWT');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Infragistics .NET Controls');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Infragistics JSF Controls');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'JSF');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Seam');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Silverlight');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Spring');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Struts');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'Swing');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'WCF');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'WF');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (3, 'WPF');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (4, '.NET');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (4, 'Java EE');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (4, 'Java SE');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (4, 'MONO');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (5, 'Linux');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (5, 'Solaris');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (5, 'Unix');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (5, 'Windows');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (6, 'MySQL');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (6, 'OpenEdge');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (6, 'Oracle');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (6, 'SQL Server');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (6, 'DB2');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (6, 'UniVerse');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (7, 'JBoss');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (7, 'Orion');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (7, 'Tomcat');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (8, 'BPEL');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (8, 'BPM');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (8, 'ESB');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (8, 'REST');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (8, 'SOA');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (8, 'SOAP');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (8, 'WS*');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (9, 'ADO');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (9, 'ADO.NET');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (9, 'Hibernate');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (9, 'nHibernate');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (10, 'JSR-168/286');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (10, 'SharePoint');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (11, 'Business Objects');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (11, 'Cognos');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (11, 'JasperSoft BI');

INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'ARIES');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Business Alerts');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Cash Flow Forecasting (CFF)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'CIBR/CMBL');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'CIS Gateway');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Collaborative Planning (CP)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'DbArchive');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'DbBACS/IP');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'DbCapture');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'DbFax');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'DbForm');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'DbScanner');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Document Imaging');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'e5');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'eAnalyser');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'eBIS Exchange');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'eFin');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'eFinance');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'eHRM');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Electronic Content Management (ECM)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Employee Expense Manager (EEM)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'eOpenPeople');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'eProcurement');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'EROS');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Financial Analytics');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'HR Pro');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'HR Pro Self Service Intranet');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'HR Pro Workflow');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Internal Self Service (ISS)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Mercury');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Open Time');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'OpenAccounts ');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'OpenPeople');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Paper Clip');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Patient Resource Management (PRM)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'People Analytics');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Purchase Card Reconciliation (PCR)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Task Scheduler');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Time Recording System (TRS)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'User Service');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Web Chart of Accounts (Web COA)');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Web Report Runner');
INSERT INTO eis_skill_item (sicategory_id, siname) VALUES (12, 'Xcel Uploader');
